import utils
import os
global RESOURCE_TYPE_ANIMATION
RESOURCE_TYPE_ANIMATION = 1
global RESOURCE_TYPE_WALLPAPER
RESOURCE_TYPE_WALLPAPER = 2
global RESOURCE_TYPE_RINGER
RESOURCE_TYPE_RINGER = 3
global RESOURCE_TYPE_APP
RESOURCE_TYPE_APP = 4
global RESOURCE_TYPE_PAPER
RESOURCE_TYPE_PAPER = 5
global QINIU_DOWNLOAD_PREFIX
QINIU_DOWNLOAD_PREFIX = 'http://7xio6q.com1.z0.glb.clouddn.com/'
global BOOTANIMATION_TMP
BOOTANIMATION_TMP = 'bootanimation_tmp/'

global MAKER_WEBSITE_URL
MAKER_WEBSITE_URL = 'http://maker.caredear.com/'

global REDIS_LOCK_HOST
global AUTO_VERSION_STATCI_PATH
if utils.is_ksyun_server() != None:
    REDIS_LOCK_HOST = 'yz-maker1'
    #AUTO_VERSION_STATCI_PATH="/opt/maker/env/maker"
    AUTO_VERSION_STATCI_PATH = os.path.dirname(os.path.dirname(
        os.path.abspath(__file__)))
else:
    AUTO_VERSION_STATCI_PATH = ""
    REDIS_LOCK_HOST = '192.168.1.13'

global REDIS_LOCK_PORT
REDIS_LOCK_PORT = 6379
global REDIS_LOCK_DB_NUM
REDIS_LOCK_DB_NUM = 0
global REDIS_LOCK_TIMEOUT
REDIS_LOCK_TIMEOUT = 30
global MAKERID_SALT
MAKERID_SALT = 'YF1B'
global CACHE_DURATION
CACHE_DURATION = 60 * 60 * 24
global MAKER_VERSION
MAKER_VERSION = '0.1.0'

global MAKER_BOOTANIMATION_INDEX_START
global MAKER_BOOTANIMATION_INDEX_END
global MAKER_AUDIO_RINGETONE
global MAKER_AUDIO_UPTONE
global MAKER_AUDIO_MESSAGETONE
global MAKER_TYPE_APP
global MAKER_PAPER_LOCKSCREEN
global MAKER_PAPER_DESKTOP
global MAKER_PAPER_ECARD

MAKER_AUDIO_RINGETONE = 1
MAKER_AUDIO_UPTONE = 2
MAKER_AUDIO_MESSAGETONE = 5
MAKER_BOOTANIMATION_INDEX_START = 1001
MAKER_BOOTANIMATION_INDEX_END = 1007
MAKER_TYPE_APP = 6
MAKER_PAPER_LOCKSCREEN = 3
MAKER_PAPER_DESKTOP = 4
MAKER_PAPER_ECARD = 7

global MAKER_DOWNLOADER_STATUS_SUCCESS
global MAKER_DOWNLOADER_STATUS_2NOTHING
global MAKER_DOWNLOADER_STATUS_ERROR
global MAKER_DOWNLOADER_STATUS_CROP_ERROR
global MAKER_DOWNLOADER_STATUS_BOOTIMG_ERROR
MAKER_DOWNLOADER_STATUS_SUCCESS = 1
MAKER_DOWNLOADER_STATUS_2NOTHING = 0
MAKER_DOWNLOADER_STATUS_ERROR = -1
MAKER_DOWNLOADER_STATUS_CROP_ERROR = -2
MAKER_DOWNLOADER_STATUS_BOOTIMG_ERROR = -3

# ERROR CODE Definition
global ERR_MAKER_SUCCESS
global ERR_MAKER_NOTFOUND
global ERR_MAKER_FILE_MISSING
global ERR_MAKER_INVALID_REQ
global ERR_MAKER_EXCEPTION
ERR_MAKER_SUCCESS = 0
ERR_MAKER_NOTFOUND = 1
ERR_MAKER_FILE_MISSING = 2
ERR_MAKER_INVALID_REQ = 3
ERR_MAKER_EXCEPTION = 4
