# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-17 15:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('uc', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corpusdata',
            name='answer',
            field=models.CharField(max_length=1024),
        ),
        migrations.AlterField(
            model_name='corpusdata',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uc.AccountProfile'),
        ),
        migrations.AlterField(
            model_name='corpusdata',
            name='question',
            field=models.CharField(max_length=255),
        ),
    ]
